// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsVrkuosvD-xZefdIjQwPRcqge_p4ZXE',
    appId: '1:348674673776:web:1d58b1cb1b49c3874378b5',
    messagingSenderId: '348674673776',
    projectId: 'rkubusguide',
    authDomain: 'rkubusguide.firebaseapp.com',
    storageBucket: 'rkubusguide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTkJ1OKjC2Ou-i-JwAdM884XZgocY3NY8',
    appId: '1:348674673776:android:acd03407662f59144378b5',
    messagingSenderId: '348674673776',
    projectId: 'rkubusguide',
    storageBucket: 'rkubusguide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6lBlM73Oh_lgw3pkgLfpr9BcqzLe2gk',
    appId: '1:348674673776:ios:fabef4d3fe768cd54378b5',
    messagingSenderId: '348674673776',
    projectId: 'rkubusguide',
    storageBucket: 'rkubusguide.appspot.com',
    iosClientId: '348674673776-10ap87m95p0k7h8eabbfk11kgqtcv43f.apps.googleusercontent.com',
    iosBundleId: 'com.example.rkuBusGuideAdmin',
  );
}
